fix_player_names <- function(player_name_vector) {
  map_chr(
    player_name_vector,
    ~ case_when(
      str_detect(., "L Jackson") ~ "Lamar Jackson",
      str_detect(., "P Mahomes") ~ "Patrick Mahomes",
      str_detect(., "J Hurts") ~ "Jalen Hurts",
      str_detect(., "K Cousins") ~ "Kirk Cousins",
      str_detect(., "R Wilson") ~ "Russell Wilson",
      str_detect(., "K Murray") ~ "Kyler Murray",
      str_detect(., "C Williams") ~ "Caleb Williams",
      str_detect(., "A Richrdson") ~ "Anthony Richardson",
      str_detect(., "T Lawrence") ~ "Trevor Lawrence",
      str_detect(., "T Tagovloa") ~ "Tua Tagovailoa",
      str_detect(., "D Jones") ~ "Daniel Jones",
      str_detect(., "S Darnold") ~ "Sam Darnold",
      str_detect(., "G Minshew") ~ "Gardner Minshew",
      str_detect(., "J Herbert") ~ "Justin Herbert",
      str_detect(., "D Prescott") ~ "Dak Prescott",
      str_detect(., "D Watson") ~ "Deshaun Watson",
      str_detect(., "B Mayfield") ~ "Baker Mayfield",
      str_detect(., "J Daniels") ~ "Jayden Daniels",
      str_detect(., "M Stafford") ~ "Matthew Stafford",
      str_detect(., "An Rodgers") ~ "Aaron Rodgers",
      str_detect(., "B Purdy") ~ "Brock Purdy",
      str_detect(., "D Henry") ~ "Derrick Henry",
      str_detect(., "I Pacheco") ~ "Isiah Pacheco",
      str_detect(., "J Hill") ~ "Jaylen Hill",
      str_detect(., "S Barkley") ~ "Saquon Barkley",
      str_detect(., "Bij Robinsn|Bija Robinson") ~ "Bijan Robinson",
      str_detect(., "N Harris") ~ "Najee Harris",
      str_detect(., "T Allgeier") ~ "Tyler Allgeier",
      str_detect(., "J Conner") ~ "James Conner",
      str_detect(., "J Cook") ~ "James Cook",
      str_detect(., "D Swift") ~ "D'Andre Swift",
      str_detect(., "K Herbert") ~ "Khalil Herbert",
      str_detect(., "T Pollard") ~ "Tony Pollard",
      str_detect(., "T Spears") ~ "Tyjae Spears",
      str_detect(., "R Stevenson") ~ "Rhamondre Stevenson",
      str_detect(., "J Taylor") ~ "Jonathan Taylor",
      str_detect(., "Joe Mixon") ~ "Joe Mixon",
      str_detect(., "DeVn Achane|Devon Achane") ~ "De'Von Achane",
      str_detect(., "R Mostert") ~ "Raheem Mostert",
      str_detect(., "T Etienne|Travis Etienne Jr") ~ "Travis Etienne",
      str_detect(., "Aaron Jones") ~ "Aaron Jones",
      str_detect(., "Singletary") ~ "Devin Singletary",
      str_detect(., "Ty Chandler") ~ "Ty Chandler",
      str_detect(., "A Kamara") ~ "Alvin Kamara",
      str_detect(., "C Hubbard") ~ "Chuba Hubbard",
      str_detect(., "G Edwards") ~ "Gus Edwards",
      str_detect(., "Zamir White") ~ "Zamir White",
      str_detect(., "Ja Williams") ~ "Javonte Williams",
      str_detect(., "K Walker|Kenneth Walker Iii") ~ "Kenneth Walker III",
      str_detect(., "E Elliott") ~ "Ezekiel Elliott",
      str_detect(., "Jerome Ford") ~ "Jerome Ford",
      str_detect(., "Rico Dowdle") ~ "Rico Dowdle",
      str_detect(., "A Ekeler") ~ "Austin Ekeler",
      str_detect(., "Bri Robinsn") ~ "Brian Robinson",
      str_detect(., "R White") ~ "Rachaad White",
      str_detect(., "D Montgmery") ~ "David Montgomery",
      str_detect(., "J Gibbs") ~ "Jahmyr Gibbs",
      str_detect(., "K Williams") ~ "Kyren Williams",
      str_detect(., "Breece Hall") ~ "Breece Hall",
      str_detect(., "C McCaffrey|Christian Mccaffrey") ~ "Christian McCaffrey",
      str_detect(., "D Samuel|Deebo Samuel") ~ "Deebo Samuel Sr.",
      str_detect(., "I Likely") ~ "Isaiah Likely",
      str_detect(., "J Watson") ~ "Jaylen Watson",
      str_detect(., "M Andrews") ~ "Mark Andrews",
      str_detect(., "M Hardman") ~ "Mecole Hardman",
      str_detect(., "N Agholor") ~ "Nelson Agholor",
      str_detect(., "Noah Gray") ~ "Noah Gray",
      str_detect(., "R Bateman") ~ "Rashod Bateman",
      str_detect(., "Rashee Rice") ~ "Rashee Rice",
      str_detect(., "T Kelce") ~ "Travis Kelce",
      str_detect(., "X Worthy") ~ "Xavier Worthy",
      str_detect(., "Zay Flowers") ~ "Zay Flowers",
      str_detect(., "A.J. Brown") ~ "A.J. Brown",
      str_detect(., "C Watson") ~ "Christian Watson",
      str_detect(., "Ceedee Lamb") ~ "CeeDee Lamb",
      str_detect(., "D Goedert") ~ "Dallas Goedert",
      str_detect(., "D Smith|Devonta Smith") ~ "DeVonta Smith",
      str_detect(., "D Wicks") ~ "Dontayvion Wicks",
      str_detect(., "Jayden Reed") ~ "Jayden Reed",
      str_detect(., "L Musgrave") ~ "Luke Musgrave",
      str_detect(., "Romeo Doubs") ~ "Romeo Doubs",
      str_detect(., "D London") ~ "Drake London",
      str_detect(., "D Mooney") ~ "Darnell Mooney",
      str_detect(., "G Pickens") ~ "George Pickens",
      str_detect(., "Kyle Pitts") ~ "Kyle Pitts",
      str_detect(., "P Freiermth") ~ "Pat Freiermuth",
      str_detect(., "D Kincaid") ~ "Dalton Kincaid",
      str_detect(., "Greg Dortch") ~ "Greg Dortch",
      str_detect(., "M Harrison|Marvin Harrison") ~ "Marvin Harrison Jr.",
      str_detect(., "M Wilson") ~ "Marquise Wilson",
      str_detect(., "T McBride|Trey Mcbride") ~ "Trey McBride",
      str_detect(., "Cole Kmet") ~ "Cole Kmet",
      str_detect(., "D.J. Chark") ~ "DJ Chark",
      str_detect(., "D Hopkins") ~ "DeAndre Hopkins",
      str_detect(., "DJ Moore") ~ "DJ Moore",
      str_detect(., "K Allen") ~ "Keenan Allen",
      str_detect(., "Rome Odunze") ~ "Rome Odunze",
      str_detect(., "D Douglas") ~ "Demario Douglas",
      str_detect(., "H Henry") ~ "Hunter Henry",
      str_detect(., "JaLynn Polk|Jalen Polk|Ja'lynn Polk") ~ "Ja'Lynn Polk",
      str_detect(., "D Schultz") ~ "Dalton Schultz",
      str_detect(., "M Pittman") ~ "Michael Pittman",
      str_detect(., "N Collins") ~ "Nico Collins",
      str_detect(., "S Diggs") ~ "Stefon Diggs",
      str_detect(., "Tank Dell") ~ "Tank Dell",
      str_detect(., "B Thomas|Brian Thomas") ~ "Brian Thomas Jr.",
      str_detect(., "C Kirk") ~ "Christian Kirk",
      str_detect(., "Evan Engram") ~ "Evan Engram",
      str_detect(., "G Davis|Gabriel Davis") ~ "Gabe Davis",
      str_detect(., "J Waddle") ~ "Jaylen Waddle",
      str_detect(., "Jonnu Smith") ~ "Jonnu Smith",
      str_detect(., "Tyreek Hill") ~ "Tyreek Hill",
      str_detect(., "J Addison") ~ "Jordan Addison",
      str_detect(., "J Jefferson") ~ "Justin Jefferson",
      str_detect(., "M Nabers") ~ "Malik Nabers",
      str_detect(., "W Robinson|Wan'dale Robinson") ~ "Wan'Dale Robinson",
      str_detect(., "A Thielen") ~ "Adam Thielen",
      str_detect(., "Chris Olave") ~ "Chris Olave",
      str_detect(., "D Johnson") ~ "Diontae Johnson",
      str_detect(., "J Johnson") ~ "Juwan Johnson",
      str_detect(., "R Shaheed") ~ "Rashid Shaheed",
      str_detect(., "D Adams") ~ "Davante Adams",
      str_detect(., "J Meyers") ~ "Jakobi Meyers",
      str_detect(., "J Palmer") ~ "Josh Palmer",
      str_detect(., "L McConkey|Ladd Mcconkey") ~ "Ladd McConkey",
      str_detect(., "C Sutton") ~ "Courtland Sutton",
      str_detect(., "DK Metcalf|Dk Metcalf") ~ "DK Metcalf",
      str_detect(., "J Reynolds") ~ "Josh Reynolds",
      str_detect(., "J S-Njigba") ~ "Jaxon Smith-Njigba",
      str_detect(., "Noah Fant") ~ "Noah Fant",
      str_detect(., "A Cooper") ~ "Amari Cooper",
      str_detect(., "David Njoku") ~ "David Njoku",
      str_detect(., "J Ferguson") ~ "Jake Ferguson",
      str_detect(., "Jerry Jeudy") ~ "Jerry Jeudy",
      str_detect(., "C Godwin") ~ "Chris Godwin",
      str_detect(., "Cade Otton") ~ "Cade Otton",
      str_detect(., "Mike Evans|Michael Evans") ~ "Mike Evans",
      str_detect(., "T McLaurin|Terry Mclaurin") ~ "Terry McLaurin",
      str_detect(., "A St. Brown") ~ "Amon-Ra St. Brown",
      str_detect(., "C Parkinson") ~ "Colby Parkinson",
      str_detect(., "Cooper Kupp") ~ "Cooper Kupp",
      str_detect(., "D Robinson") ~ "Demarcus Robinson",
      str_detect(., "Jmn Wiliams") ~ "Jameson Williams",
      str_detect(., "Puka Nacua") ~ "Puka Nacua",
      str_detect(., "Sam LaPorta|Sam Laporta") ~ "Sam LaPorta",
      str_detect(., "B Aiyuk") ~ "Brandon Aiyuk",
      str_detect(., "G Kittle") ~ "George Kittle",
      str_detect(., "G Wilson") ~ "Garrett Wilson",
      str_detect(., "J Jennings") ~ "Jauan Jennings",
      str_detect(., "K Juszczyk") ~ "Kyle Juszczyk",
      str_detect(., "T Conklin") ~ "Tyler Conklin",
      TRUE ~ . # Default case to return the original player name
    )
  )
}